from setuptools import setup, find_packages

setup(
    name='tmap_pmc',
    version='0.1.0',  
    author='Alejandro Flores',   
    author_email='afloresep01@gmail.com',   
    description='TMAP tokenizing Target descriptions from ChEMBL data',
    long_description=open('README.md').read(),   
    long_description_content_type='text/markdown',
    url='https://github.com/afloresep/tmap_pmc',  
    packages=find_packages(where='src'),   
    package_dir={'': 'src'},   
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7.12',  # Specifies the exact Python version
    install_requires=[
        'autocommand==2.2.2',
        'certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1725278078093/work/certifi',
        'cheroot==10.0.1',
        'CherryPy==18.10.0',
        'click==8.1.7',
        'colorama==0.4.6',
        'colour==0.1.5',
        'cycler==0.11.0',
        'faerun==0.4.7',
        'fonttools==4.38.0',
        'importlib-metadata==6.7.0',
        'importlib-resources==5.12.0',
        'inflect==6.0.5',
        'jaraco.collections==4.2.0',
        'jaraco.context==4.3.0',
        'jaraco.functools==3.7.0',
        'jaraco.text==3.11.1',
        'Jinja2==3.1.4',
        'joblib==1.3.2',
        'kiwisolver==1.4.5',
        'mapchiral==0.0.5',
        'MarkupSafe==2.1.5',
        'matplotlib==3.5.3',
        'mhfp==1.9.6',
        'more-itertools==9.1.0',
        'nltk==3.8.1',
        'numpy==1.21.6',
        'packaging==24.0',
        'pandas==1.3.5',
        'Pillow==9.5.0',
        'portend==3.1.0',
        'pydantic==1.10.18',
        'pyparsing==3.1.4',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.2',
        'pywin32==306',
        'rdkit==2023.3.2',
        'regex==2024.4.16',
        'six==1.16.0',
        'tempora==5.3.0',
        'tmap==1.0.6',
        'tqdm==4.66.5',
        'typing_extensions==4.7.1',
        'ujson==5.7.0',
        'wincertstore==0.2',
        'zc.lockfile==3.0.post1',
        'zipp==3.15.0',
    ]
)
